version: '3.5'
services:
    cerithapi:
        build: .
        image: cerithapi:dev
        ports:
        - "60000:60000"
        environment:
        - "CERITH_CONFIG_KEY=cerith.nucleus.dev"
        - "CONSUL_URL=http://host.docker.internal:8501/"
        container_name: cerithapi-dev2
